### PR TITLE
fix: suppression insee et recherche entreprise nom commercial

### LINKED ISSUE #1228: Nom commercial
Exemple : 487566606 « SUPPRESSION DU NOM COMMERCIAL ». Probablement un raccourci pris par l'Insee

https://annuaire-entreprises.data.gouv.fr/entreprise/487566606

Todo : 
- ignorer les noms commerciaux `SUPPRESSION DU NOM COMMERCIAL` dans le code du site et de l'API
- informer Anais quand c'est en prod pour qu'elle puisse répondre au ticket

### PR DESCRIPTION
**Pull request by rmonnier9**
- Correction d'un bug
- Zones impactées : `./models/core/unite-legal.ts`.
- Détails :
  - Nettoyage à la volée de la mention "suppression du nom commercial"

closes #1228

### CODE REVIEW

**Review by XavierJp — CHANGES_REQUESTED** [review]
Works pretty well but I would rather suggest a different approach, removing `SUPPRESSION DU NOM COMMERCIAL` directly in the underlying clients rather than i the model

**Comment by rmonnier9** [comment]
The fix is now at the client level.

Is it the correct approach ?
I thought maybe you were referring to an empty field ?

**Comment by rmonnier9** [comment]
I fixed the ‘recherche entreprise’ result, but this might be redundant with the upcoming fix from Hajar.

**Comment by rmonnier9** [comment]
In the example I was using, only “enseigne1Etablissement” was affected, but in case the others can be affected as well, I applied the format function to all three.

**Review by XavierJp — APPROVED** [review]

**Pull request merged**
