### PR TITLE
fix: don't use reconnect banner on static pages

### LINKED ISSUE #1489: [BUG] Session are not included in header in some pages
## Probleme
Several pages lack session and therefore user is not connected. This can mess up the reconnexion banner logic.

https://annuaire-entreprises.data.gouv.fr/donnees/api
https://annuaire-entreprises.data.gouv.fr/stats

### PR DESCRIPTION
**Pull request by rmonnier9**
- Correction d'un bug.
- Détails :
  - Création d'un nouveau layout qui n'utilise pas la bannière de reconnexion
  - Le layout est utilisé pour les deux pages statiques (généré au moment du build)

Closes #1489

Page /stats :
image

### CODE REVIEW

**Review by XavierJp — APPROVED** [review]

**Review by XavierJp — COMMENTED** [review]
I think layout name can be improved for readibility

**Comment by XavierJp** [comment]
Especially as you did not rename `LayoutWithSearchBar`

You can add comments or a more explicit naming to explain why we deactivate this banner here

**Comment by rmonnier9** [comment]
> Especially as you did not rename `LayoutWithSearchBar`
> 
> You can add comments or a more explicit naming to explain why we deactivate this banner here

I named it LayoutPublic and header-public
I added this description :
/**
 * Layout component designed for pages without authentication.
 * It is mainly used for static pages as they can't access the session.
 **/

**Review by XavierJp — APPROVED** [review]
I love it with comment and this explicit naming

**Pull request merged**
